language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
env:
  matrix:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-1.11.3
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  global:
    secure: UqolzT6Ki+DIWBjGJ89GG0ei1ppwIbZiKkdHF/Ib8FBljonCQJ4HxEDQRLDquvO5nOXcfwL+YMuic0LlMPjf8plgh41dXIsQ2zeHxX8tsrpBEOBoOWvR6YS734CVf7k+WQRBluFBseF8BWW2oKvgPCtTgLd7UpBVoF3taTSySqg=

matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-beta
  - env: EMBER_TRY_SCENARIO=ember-canary

<<<<<<< Updated upstream
=======
branches:
  only:
    - main

>>>>>>> Stashed changes
before_install:
- mkdir travis-phantomjs
- wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
- tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
- export PATH=$PWD/travis-phantomjs:$PATH
- npm config set spin false
- npm install -g npm@^2

install:
- npm install -g bower
- npm install
- bower install

script:
- ember try $EMBER_TRY_SCENARIO test
